ROBOT = "g1"
ROBOT_SCENE = "../unitree_robots/" + ROBOT + "/scene_29dof.xml"
DOMAIN_ID = 0
INTERFACE = "wlp9s0" # ADD WLAN PORT INDIVIDUALLY

USE_JOYSTICK = 1
JOYSTICK_TYPE = "xbox"
JOYSTICK_DEVICE = 0

PRINT_SCENE_INFORMATION = True
ENABLE_ELASTIC_BAND = True

SIMULATE_DT = 0.002
VIEWER_DT = 0.02
